name: boulderrun
title: Boulder Run
version: '1.8.1'
summary: Boulder Dash clone on Java
description: |
Run, dig, make traps! You are playing miner and you need to mine emeralds, but in caves you can find pythons!

base: core18
confinement: strict

apps:
  boulderrun:
    extensions:
      - gnome-3-28
    command: boulderrun-java -jar $SNAPCRAFT_PROJECT_VERSION/build/libs/boulderrun-1.0-SNAPSHOT.jar
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - cups-control

parts:
  boulderrun:
    plugin: gradle
    source: https://github.com/timaaos/boulderrun.git
    source-tag: release-$SNAPCRAFT_PROJECT_VERSION
    gradle-version: '5.1.1'
    gradle-output-dir: BIN
    gradle-options: [-xtest, -xcreateGitTag]
