name: boulderrun # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Boulder Dash clone on Java # 79 char long summary
description: |
  Dig, run, make traps! You need to collect all diamonds to win!

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  boulderrun:
    # See 'snapcraft plugins'
    plugin: gradle
    source: https://github.com/timaaos/boulderrun.git
    source-type: git
    gradle-options: []   # suppress running of tests and run the war task
    gradle-output-dir: build/libs
